cross build --release
cross build --release --target aarch64-linux-android
cross build --release --target aarch64-unknown-linux-gnu
cross build --release --target aarch64-unknown-linux-musl
cross build --release --target arm-linux-androideabi
cross build --release --target arm-unknown-linux-gnueabi
cross build --release --target arm-unknown-linux-gnueabihf
cross build --release --target arm-unknown-linux-musleabi
cross build --release --target arm-unknown-linux-musleabihf
cross build --release --target armv5te-unknown-linux-gnueabi
cross build --release --target armv5te-unknown-linux-musleabi
cross build --release --target armv7-linux-androideabi
cross build --release --target armv7-unknown-linux-gnueabihf
cross build --release --target armv7-unknown-linux-musleabihf
cross build --release --target i586-unknown-linux-gnu
cross build --release --target i586-unknown-linux-musl
cross build --release --target i686-unknown-freebsd
cross build --release --target i686-linux-android
cross build --release --target i686-pc-windows-gnu
cross build --release --target i686-unknown-linux-gnu
cross build --release --target i686-unknown-linux-musl
cross build --release --target mips-unknown-linux-gnu
cross build --release --target mips-unknown-linux-musl
cross build --release --target mips64-unknown-linux-gnuabi64
cross build --release --target mips64el-unknown-linux-gnuabi64
cross build --release --target mipsel-unknown-linux-gnu
cross build --release --target mipsel-unknown-linux-musl
cross build --release --target powerpc-unknown-linux-gnu
cross build --release --target powerpc64-unknown-linux-gnu
cross build --release --target powerpc64le-unknown-linux-gnu
cross build --release --target riscv64gc-unknown-linux-gnu
cross build --release --target s390x-unknown-linux-gnu
cross build --release --target sparc64-unknown-linux-gnu
cross build --release --target sparcv9-sun-solaris
cross build --release --target thumbv6m-none-eabi
cross build --release --target thumbv7em-none-eabi
cross build --release --target thumbv7em-none-eabihf
cross build --release --target thumbv7m-none-eabi
cross build --release --target wasm32-unknown-emscripten
cross build --release --target x86_64-linux-android
cross build --release --target x86_64-sun-solaris
cross build --release --target x86_64-unknown-freebsd
cross build --release --target x86_64-unknown-dragonfly
cross build --release --target x86_64-unknown-linux-gnu
cross build --release --target x86_64-unknown-linux-musl
cross build --release --target x86_64-unknown-netbsd