[package]
name = "nextlaunch"
version = "0.2.31"
description = "Watch a countdown until the next rocket launch, live in your terminal!"
authors = ["AltriusRS <tom.b.2k2@gmail.com>"]
edition = "2018"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]
repository = "https://github.com/AltriusRS/NextLaunch"
keywords = [
    "space",
    "cli",
    "terminal",
    "spacex",
    "countdown"
]
license = "MIT"
readme = "README.md"

[dependencies]
reqwest = { version="0.11.0", features = ["blocking", "serde_json", "json"] }
serde = { version="1.0.123", features = ["derive"] }
image = "0.23.12"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
bincode = "1.3.1"
