[package]
name = "nextlaunch"
version = "0.2.0"
description = "Watch a countdown until the next rocket launch, live in your terminal!!"
authors = ["fatalcenturion <tom.b.2k2@gmail.com>"]
edition = "2018"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]
repository = "https://github.com/fatalcenturion/NextLaunch"
keywords = [
    "space",
    "cli",
    "terminal",
    "spacex",
    "countdown"
]
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version="0.10.9", features = ["blocking", "serde_json", "json"] }
serde = { version="1.0.117", features = ["derive"] }
serde_json = "1.0.0"
proctitle = "0.1.1"
bytes = "0.6.0"
image = "0.14.0"
chrono = "0.4.19"
clap = "3.0.0-beta.2"