[package]
name = "nextlaunch"
version = "0.3.0"
description = "Watch a countdown until the next rocket launch, live in your terminal!"
authors = ["AltriusRS <tom.b.2k2@gmail.com>"]
edition = "2018"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]
repository = "https://github.com/AltriusRS/NextLaunch"
keywords = [
    "space",
    "cli",
    "terminal",
    "spacex",
    "countdown"
]
license = "MIT"
readme = "README.md"

[dependencies]
reqwest = { version = "0.11.0", features = ["serde_json", "json"] }
serde = { version = "1.0.123", features = ["derive"] }
chrono = "0.4.19"
bincode = "1.3.1"
websocket = "0.26.2"
terminal_size = "0.1.16"
tokio = { version = "1.1.1", features = ["full"] }